-- Users: внутренние пользователи бота
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- User identities: сопоставление транспорта и внешнего id к внутреннему user_id
CREATE TABLE IF NOT EXISTS user_identities (
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    transport   TEXT   NOT NULL,
    external_id TEXT   NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (transport, external_id)
);

CREATE INDEX IF NOT EXISTS idx_user_identities_user_id
    ON user_identities(user_id);

-- Incomes: доходы в минимальных денежных единицах (копейки)
CREATE TABLE IF NOT EXISTS incomes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    at          DATE   NOT NULL,                                -- дата дохода (локальный день)
    amount      BIGINT NOT NULL CHECK (amount >= 0),            -- сумма в копейках
    note        TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_incomes_user_at
    ON incomes(user_id, at);
